/* Auto-generated by generate.py. Do NOT edit by hand.
 * Change the master list in generate.py and re-run it. */
#include <stddef.h>
#include <stdint.h>

#include "tokens.h"

/* When `types` is NULL, count only (pass 1); otherwise fill spans (pass 2).
 * Scans the buffer in place; buf[len] must be a NUL sentinel. */
static size_t scan(const char *buf, size_t len,
                   int32_t *types, int32_t *starts, int32_t *lens)
{
    const unsigned char *base = (const unsigned char *)buf;
    const unsigned char *cur  = base;
    const unsigned char *lim  = base + len;
    const unsigned char *mar;
    const unsigned char *tok;
    size_t n = 0;

    #define EMIT(t) do { if (types) { types[n]=(t); starts[n]=(int32_t)(tok-base); \
                                      lens[n]=(int32_t)(cur-tok); } n++; } while (0)

    for (;;) {
        tok = cur;
        /*!re2c
            re2c:define:YYCTYPE  = "unsigned char";
            re2c:define:YYCURSOR = cur;
            re2c:define:YYLIMIT  = lim;
            re2c:define:YYMARKER = mar;
            re2c:yyfill:enable   = 0;
            re2c:eof             = 0;

            [ \t\r\n\f\v"]+                                             { continue; }
            ("#" | "%") [^\n]*                                              { continue; }
            "show-concrete-instance-for" { EMIT(KW_SHOW_CONCRETE_INSTANCE_FOR); continue; }
            "define-fuzzy-number-range"  { EMIT(KW_DEFINE_FUZZY_NUMBER_RANGE); continue; }
            "show-abstract-fillers-for"  { EMIT(KW_SHOW_ABSTRACT_FILLERS_FOR); continue; }
            "show-concrete-fillers-for"  { EMIT(KW_SHOW_CONCRETE_FILLERS_FOR); continue; }
            "define-fuzzy-equivalence"   { EMIT(KW_DEFINE_FUZZY_EQUIVALENCE); continue; }
            "define-primitive-concept"   { EMIT(KW_DEFINE_PRIMITIVE_CONCEPT); continue; }
            "define-fuzzy-similarity"    { EMIT(KW_DEFINE_FUZZY_SIMILARITY); continue; }
            "define-truth-constant"      { EMIT(KW_DEFINE_TRUTH_CONSTANT); continue; }
            "show-abstract-fillers"      { EMIT(KW_SHOW_ABSTRACT_FILLERS); continue; }
            "show-concrete-fillers"      { EMIT(KW_SHOW_CONCRETE_FILLERS); continue; }
            "define-fuzzy-concept"       { EMIT(KW_DEFINE_FUZZY_CONCEPT); continue; }
            "define-fuzzy-number"        { EMIT(KW_DEFINE_FUZZY_NUMBER); continue; }
            "equivalent-concepts"        { EMIT(KW_EQUIVALENT_CONCEPTS); continue; }
            "triangular-modifier"        { EMIT(KW_TRIANGULAR_MODIFIER); continue; }
            "define-fuzzy-logic"         { EMIT(KW_DEFINE_FUZZY_LOGIC); continue; }
            "inverse-functional"         { EMIT(KW_INVERSE_FUNCTIONAL); continue; }
            "define-modifier"            { EMIT(KW_DEFINE_MODIFIER); continue; }
            "linear-modifier"            { EMIT(KW_LINEAR_MODIFIER); continue; }
            "all-instances?"             { EMIT(KW_ALL_INSTANCES_QUERY); continue; }
            "define-concept"             { EMIT(KW_DEFINE_CONCEPT); continue; }
            "defuzzify-lom?"             { EMIT(KW_DEFUZZIFY_LOM_QUERY); continue; }
            "defuzzify-mom?"             { EMIT(KW_DEFUZZIFY_MOM_QUERY); continue; }
            "defuzzify-som?"             { EMIT(KW_DEFUZZIFY_SOM_QUERY); continue; }
            "disjoint-union"             { EMIT(KW_DISJOINT_UNION); continue; }
            "right-shoulder"             { EMIT(KW_RIGHT_SHOULDER); continue; }
            "show-instances"             { EMIT(KW_SHOW_INSTANCES); continue; }
            "show-variables"             { EMIT(KW_SHOW_VARIABLES); continue; }
            "crisp-concept"              { EMIT(KW_CRISP_CONCEPT); continue; }
            "left-shoulder"              { EMIT(KW_LEFT_SHOULDER); continue; }
            "max-instance?"              { EMIT(KW_MAX_INSTANCE_QUERY); continue; }
            "min-instance?"              { EMIT(KW_MIN_INSTANCE_QUERY); continue; }
            "show-concepts"              { EMIT(KW_SHOW_CONCEPTS); continue; }
            "show-language"              { EMIT(KW_SHOW_LANGUAGE); continue; }
            "implies-role"               { EMIT(KW_IMPLIES_ROLE); continue; }
            "max-kd-subs?"               { EMIT(KW_MAX_KD_SUBS_QUERY); continue; }
            "max-related?"               { EMIT(KW_MAX_RELATED_QUERY); continue; }
            "min-kd-subs?"               { EMIT(KW_MIN_KD_SUBS_QUERY); continue; }
            "min-related?"               { EMIT(KW_MIN_RELATED_QUERY); continue; }
            "constraints"                { EMIT(KW_CONSTRAINTS); continue; }
            "lukasiewicz"                { EMIT(KW_LUKASIEWICZ); continue; }
            "max-g-subs?"                { EMIT(KW_MAX_G_SUBS_QUERY); continue; }
            "max-l-subs?"                { EMIT(KW_MAX_L_SUBS_QUERY); continue; }
            "min-g-subs?"                { EMIT(KW_MIN_G_SUBS_QUERY); continue; }
            "min-l-subs?"                { EMIT(KW_MIN_L_SUBS_QUERY); continue; }
            "sigma-count"                { EMIT(KW_SIGMA_COUNT); continue; }
            "trapezoidal"                { EMIT(KW_TRAPEZOIDAL); continue; }
            "crisp-role"                 { EMIT(KW_CRISP_ROLE); continue; }
            "functional"                 { EMIT(KW_FUNCTIONAL); continue; }
            "kd-implies"                 { EMIT(KW_KLEENE_DIENES_IMPLIES); continue; }
            "transitive"                 { EMIT(KW_TRANSITIVE); continue; }
            "triangular"                 { EMIT(KW_TRIANGULAR); continue; }
            "w-sum-zero"                 { EMIT(KW_W_SUM_ZERO); continue; }
            "*boolean*"                  { EMIT(KW_BOOLEAN); continue; }
            "classical"                  { EMIT(KW_CLASSICAL); continue; }
            "g-implies"                  { EMIT(KW_GOEDEL_IMPLIES); continue; }
            "*integer*"                  { EMIT(KW_INTEGER); continue; }
            "l-implies"                  { EMIT(KW_LUKASIEWICZ_IMPLIES); continue; }
            "max-subs?"                  { EMIT(KW_MAX_SUBS_QUERY); continue; }
            "min-subs?"                  { EMIT(KW_MIN_SUBS_QUERY); continue; }
            "reflexive"                  { EMIT(KW_REFLEXIVE); continue; }
            "symmetric"                  { EMIT(KW_SYMMETRIC); continue; }
            "z-implies"                  { EMIT(KW_ZADEH_IMPLIES); continue; }
            "*bottom*"                   { EMIT(KW_BOTTOM); continue; }
            "disjoint"                   { EMIT(KW_DISJOINT); continue; }
            "instance"                   { EMIT(KW_INSTANCE); continue; }
            "max-sat?"                   { EMIT(KW_MAX_SAT_QUERY); continue; }
            "max-var?"                   { EMIT(KW_MAX_VAR_QUERY); continue; }
            "min-sat?"                   { EMIT(KW_MIN_SAT_QUERY); continue; }
            "min-var?"                   { EMIT(KW_MIN_VAR_QUERY); continue; }
            "modified"                   { EMIT(KW_MODIFIED); continue; }
            "q-sugeno"                   { EMIT(KW_QUASI_SUGENO); continue; }
            "*string*"                   { EMIT(KW_STRING); continue; }
            "choquet"                    { EMIT(KW_CHOQUET); continue; }
            "implies"                    { EMIT(KW_IMPLIES); continue; }
            "inverse"                    { EMIT(KW_INVERSE); continue; }
            "related"                    { EMIT(KW_RELATED); continue; }
            "binary"                     { EMIT(KW_BINARY); continue; }
            "domain"                     { EMIT(KW_DOMAIN); continue; }
            "b-some"                     { EMIT(KW_HAS_VALUE); continue; }
            "linear"                     { EMIT(KW_LINEAR); continue; }
            "*real*"                     { EMIT(KW_REAL); continue; }
            "sugeno"                     { EMIT(KW_SUGENO); continue; }
            "crisp"                      { EMIT(KW_CRISP); continue; }
            "g-and"                      { EMIT(KW_GOEDEL_AND); continue; }
            "l-and"                      { EMIT(KW_LUKASIEWICZ_AND); continue; }
            "q-owa"                      { EMIT(KW_Q_OWA); continue; }
            "range"                      { EMIT(KW_RANGE); continue; }
            "*top*"                      { EMIT(KW_TOP); continue; }
            "w-max"                      { EMIT(KW_W_MAX); continue; }
            "w-min"                      { EMIT(KW_W_MIN); continue; }
            "w-sum"                      { EMIT(KW_W_SUM); continue; }
            "zadeh"                      { EMIT(KW_ZADEH); continue; }
            "bnp?"                       { EMIT(KW_BNP_QUERY); continue; }
            "free"                       { EMIT(KW_FREE); continue; }
            "g-or"                       { EMIT(KW_GOEDEL_OR); continue; }
            "l-or"                       { EMIT(KW_LUKASIEWICZ_OR); continue; }
            "sat?"                       { EMIT(KW_SAT_QUERY); continue; }
            "self"                       { EMIT(KW_SELF); continue; }
            "some"                       { EMIT(KW_SOME); continue; }
            "all"                        { EMIT(KW_ALL); continue; }
            "and"                        { EMIT(KW_AND); continue; }
            "lla"                        { EMIT(KW_LOOSE_LOWER_APPROXIMATION); continue; }
            "lua"                        { EMIT(KW_LOOSE_UPPER_APPROXIMATION); continue; }
            "not"                        { EMIT(KW_NOT); continue; }
            "owa"                        { EMIT(KW_OWA); continue; }
            "tla"                        { EMIT(KW_TIGHT_LOWER_APPROXIMATION); continue; }
            "tua"                        { EMIT(KW_TIGHT_UPPER_APPROXIMATION); continue; }
            "la"                         { EMIT(KW_LOWER_APPROXIMATION); continue; }
            "or"                         { EMIT(KW_OR); continue; }
            "ua"                         { EMIT(KW_UPPER_APPROXIMATION); continue; }
            "("                          { EMIT(T_LPAREN); continue; }
            ")"                          { EMIT(T_RPAREN); continue; }
            "["                          { EMIT(T_LBRACK); continue; }
            "]"                          { EMIT(T_RBRACK); continue; }
            "{"                          { EMIT(T_LBRACE); continue; }
            "}"                          { EMIT(T_RBRACE); continue; }
            ","                          { EMIT(T_COMMA); continue; }
            ">="                         { EMIT(KW_GREATER_THAN_OR_EQUAL_TO); continue; }
            "<="                         { EMIT(KW_LESS_THAN_OR_EQUAL_TO); continue; }
            "="                          { EMIT(KW_EQUALS); continue; }
            "f+"                         { EMIT(KW_FEATURE_SUM); continue; }
            "f-"                         { EMIT(KW_FEATURE_SUB); continue; }
            "f*"                         { EMIT(KW_FEATURE_MUL); continue; }
            "f/"                         { EMIT(KW_FEATURE_DIV); continue; }
            "+"                          { EMIT(KW_SUM); continue; }
            "-"                          { EMIT(KW_SUB); continue; }
            "*"                          { EMIT(KW_MUL); continue; }
            [+-]?[0-9]+("." [0-9]*)?([eE][+-]?[0-9]+)?                             { EMIT(T_NUMBER); continue; }
            [a-zA-Z0-9_><][a-zA-Z0-9_'/.:><@$!?-]*                                 { EMIT(T_IDENT); continue; }
            $                                                                      { break; }
            *                                                                      { EMIT(T_ERROR); continue; }
        */
    }
    #undef EMIT
    return n;
}

size_t fdl_count_tokens(const char *buf, size_t len) { return scan(buf, len, NULL, NULL, NULL); }
size_t fdl_tokenize(const char *buf, size_t len,
                    int32_t *types, int32_t *starts, int32_t *lens) {
    return scan(buf, len, types, starts, lens);
}