from fuzzy_dl_owl2.test.parser_interface import *

from .test_absorption import *
from .test_aggregation import *
from .test_all import *
from .test_and import *
from .test_blocking import *
from .test_datatype import *
from .test_disjoint import *
from .test_functional import *
from .test_fuzzy_concrete_domain import *
from .test_fuzzy_number import *
from .test_implies import *
from .test_implies_role import *
from .test_inconsistency import *
from .test_instance import *
from .test_inverse import *
from .test_modifier import *
from .test_not import *
from .test_or import *
from .test_reflexive import *
from .test_related import *
from .test_rough_sets import *
from .test_sat import *
from .test_self import *
from .test_show_statement import *
from .test_some import *
from .test_subsumption import *
from .test_symmetric import *
from .test_tbox import *
from .test_threshold_concept import *
from .test_transitive import *
from .test_truth_constant import *
from .test_weighted_concept import *
from .test_weighted_sum import *
